name = "hellobusan"
main = "src/worker.js"
compatibility_date = "2026-09-24"
compatibility_flags = ["nodejs_compat"]

[assets]
directory = "."
binding = "ASSETS"

[[send_email]]
name = "SEND_EMAIL"
destination_address = "jenny@thesonlab.com"
